### ISSUE TITLE
Installation returns unexpected error on MacBook.

### ISSUE THREAD

**Issue by Mr-HoDL58** [pactus-project/pactus-gui#16]
[C.txt](https://github.com/user-attachments/files/16320875/C.txt)
Error report in link above.

**Comment by amirvalhalla** [comment]
Hi @Mr-HoDL58,
---

I figured out the reason for your issue based on the log report below:

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/glib/lib/libgmodule-2.0.0.dylib
```

It seems that you did not install the `glib` library on your macOS Sonoma (14.5). Please try to install it by running the command below:

```bash
brew install glib
```

Also, make sure that the `brew` path is in your `PATH` environment variable. To do this, you can append the following command to your `.zshrc` or `.bashrc` file located in your `HOME` directory.

**Note:** To apply your new configuration, you need to open a new terminal session.

After you have installed `glib` with `brew`, it will exist at the `/opt/homebrew/opt/glib` path. Because Pactus will search for the `glib` library at `/usr/local/opt`, you should follow the steps below after installing `glib` with `brew`:

1. `sudo mkdir -p /usr/local/opt`
2. `sudo ln -s /opt/homebrew/opt/glib /usr/local/opt/glib`

Now, you should be able to run `pactus-gui`. Please provide us with feedback on whether it works fine or not.

Thanks!

**Comment by b00f** [comment]
@amirvalhalla 
That is too technical. Most of users are not familiar with this. Let's find better way.

@Mr-HoDL58 
Do you think they run Pactus using DMG or Gzip. We recommend use DMG that include all the dependencies:

![image](https://github.com/user-attachments/assets/a2c8dcbc-94cc-487a-be8d-531561e31f2f)
