### ISSUE TITLE
Refactor and align text styles in themes with Figma design specifications

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [pactus-project/pactus-gui#34]
## Overview
**Component/Feature:** Text styles used across the application.  
**Reason:** The current text styles do not align with the Figma design specifications, leading to inconsistencies in typography and overall UI cohesion. A refactor is required to ensure design fidelity and maintainability.

## Goals
- Achieve consistency between the application's text styles and the Figma design.  
- Improve maintainability by consolidating text styles into a centralized, reusable format.  
- Ensure better readability and user experience through adherence to the design system.

## Proposed Changes
- Audit all existing text styles used in the application.  
- Identify discrepancies between the current styles and those defined in the Figma design.  
- Refactor the text styles into a unified structure, leveraging theme-based styling (e.g., `TextTheme` in Flutter).  
- Replace hardcoded styles with the updated reusable styles across the codebase.

## Design Reference
- **Figma Design:** [Link to Figma Design](https://www.figma.com/design/o4xKRt7MeSuyjIMOxU1U5v/Pactus-Applications-(Community)?node-id=0-1&node-type=canvas&t=axM2jYbzZYXJdXmK-0)  
  The Figma design includes updated typography specifications such as font families, weights, sizes, and line heights for various text elements. Ensure strict adherence to these specifications.
  
  ## Related Issues
- [issue #25](https://github.com/pactus-project/pactus-gui/issues/25): Implement Theme Management .

**Comment by PouriaMoradi021** [comment]
### 📊 Current Status:
**Progress**: 0%

- ✔️ Completed Tasks:
  - [ ] Task 1: extract text styles from figma design 
  - [ ] Task 2: add text styles  to app



### 🚧 Challenges/Blockers:
- Not identified

### 🛤️ Next Steps:
- Estimated time for completion: -

### ❓ Questions/Requests:

----

@esmaeil-ahmadipour

**Comment by PouriaMoradi021** [comment]
All text styles used in the Figma design were extracted and the result was as follows :
| -----| weight | size | height      | name         |
|------|--------|------|-------------|--------------|
| 1    | 200    | 4    | 10/4 = 2.5  | extraLight4  |
| 2    | 200    | 6    | 16/6 = 2.67 | extraLight6  |
| 3    | 200    | 14   | 28/14 = 2   | extraLight14 |
| 4    | 200    | 15   | 24/15 = 1.6 | extraLight15 |
| 5    | 200    | 30   | 44/30 = 1.47| extraLight30 |
| 6    | 300    | 9    | 15/9 = 1.67 | light9       |
| 7    | 300    | 10   | 20/10 = 2   | light10      |
| 8    | 300    | 14   | 20/14 = 1.43| light14      |
| 9    | 300    | 15   | 24/15 = 1.6 | light15      |
| 10   | 300    | 18   | 24/18 = 1.33| light18      |
| 11   | 400    | 8    | 20/8 = 2.5  | regular8     |
| 12   | 400    | 10   | 20/10 = 2   | regular10H2    |
| 13   | 400    | 10   | 16/10 = 1.6 | regular10H1    |
| 14   | 400    | 11   | 18/11 = 1.64| regular11H1    |
| 15   | 400    | 11   | 20/11 = 1.82| regular11H2    |
| 16   | 400    | 12   | 20/12 = 1.67| regular12H2    |
| 17   | 400    | 12   | 16/12 = 1.33| regular12H1    |
| 18   | 400    | 13   | 25/13 = 1.92| regular13H3    |
| 19   | 400    | 14   | 20/14 = 1.43| regular14H1    |
| 20   | 400    | 14   | 28/14 = 2   | regular14H2    |
| 21   | 500    | 11   | 20/11 = 1.82| medium11     |
| 22   | 500    | 12   | 20/12 = 1.67| medium12H2     |
| 23   | 500    | 12   | 17/12 = 1.42| medium12H1     |
| 24   | 500    | 13   | 16/13 = 1.23| medium13     |
| 25   | 500    | 14   | 20/14 = 1.43| medium14     |
| 26   | 600    | 7    | 20/7 = 2.86 | semiBold7    |
| 27   | 600    | 10   | 20/10 = 2   | semiBold10   |
| 28   | 600    | 14   | 16/14 = 1.14| semiBold14H1   |
| 29   | 600    | 14   | 24/14 = 1.71| semiBold14H2   |
| 30   | 600    | 14   | 28/14 = 2   | semiBold14H2  |
| 31   | 600    | 14   | 20/14 = 1.43| semiBold14H1   |
| 32   | 600    | 16   | 24/16 = 1.5 | semiBold16   |
| 33   | 600    | 24   | 32/24 = 1.33| semiBold24   |
| 34   | 700    | 9    | 20/9 = 2.22 | bold9        |
| 35   | 700    | 10   | 20/10 = 2   | bold10       |
| 36   | 700    | 12   | 20/12 = 1.67| bold12       |
| 37   | 700    | 13   | 16/13 = 1.23| bold13       |
| 38   | 700    | 14   | 28/14 = 2   | bold14       |

also for text styles that are from the same family and have the same weight but different heights, such as:
```
static const TextStyle regular10H1 = TextStyle(
    fontFamily: interRegular,
    fontSize: 10,
    fontWeight: FontWeight.w400,
    height: 1.6, // Equivalent to 16/10
  );

  static const TextStyle regular10H2 = TextStyle(
    fontFamily: interRegular,
    fontSize: 10,
    fontWeight: FontWeight.w400,
    height: 2.0, // Equivalent to 20/10
  );

```
The `H` tag is used to distinguish between different heights of a size. For example, in the code above, `Regular` size 10 with a height of `1.6` is specified with the `H1` tag and with a height of `2` is specified with the `H2` tag.

But the important thing is that these fonts should be named by the UI team and documented in the Figma design so that they can be used correctly in the code. Since this was not done, this naming was done by myself based on the font family of each text and it is recommended that the UI team member use this naming convention and place these names in the design.

-------
@esmaeil-ahmadipour  @Ja7ad  @phoenixit99

**Comment by esmaeil-ahmadipour** [comment]
Document the Text Style Names
Ensure you document the name of each text style above it. This will make it easier to locate and reference them.

---

@PouriaMoradi021

**Comment by esmaeil-ahmadipour** [comment]
Everything done in this issue has been implemented correctly, but when used in the appropriate places, it encounters issues.

According to Material Design 3, there are only 15 defined text styles, and using more than that is not standard. Therefore, to align with the design system, some adjustments are needed from the design team to reduce the number of text styles.

As a result, this issue should be moved to the backlog until the necessary changes are made.

---

@PouriaMoradi021  / @phoenixit99  / @Ja7ad
